### ISSUE TITLE
Default icon border radius

### ISSUE THREAD

**Issue by Nekomajin42** [RunninglVlan/Facebook-Status#1]
Hey!

Thanks for this extension! I like how simple it is. However, could you change the default icon to have a few pixels of border radius? Something like the icon on Facebook on the top left, next to the search field. The color is great, but it's too square.

**Comment by RunninglVlan** [comment]
Hi, thanks for your kind words, and good idea.
Initially default icon was made from [this SVG](https://m.facebook.com/icon.svg) that is the icon of mobile Facebook site. I compared it using the same scale to [this ICO](https://static.xx.fbcdn.net/rsrc.php/yl/r/H3nktOa7ZMg.ico) that is the icon of desktop site, and they had the same rounded corners.
But I also like corners of the white Facebook icon from [here](https://static.xx.fbcdn.net/rsrc.php/v2/yo/r/wrR7iqNaVFE.png) more so I'll update the icon.
Although as this is such a small change, I won't update the extension right away. I will update it in February though. ;)

**Comment by Nekomajin42** [comment]
Thanks!
