### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Aleck85** [RunninglVlan/Facebook-Status#13]
Не работает расширение. Firefox 90. 
![Снимок экрана (1)](https://user-images.githubusercontent.com/5072865/128384252-8a74f509-07c5-4382-92d2-2d0faac005cc.jpg)

**Comment by RunninglVlan** [comment]
Спасибо, пофиксил. Что-то Firefox начал возвращать странички с ошибками в расширении. Надеюсь, это временно, так как я ещё пофиксил поддержку login page (раньше расширение ошибку показывала, что надо залогиниться), где он сейчас тоже ошибку возвращает.

**Comment by RunninglVlan** [comment]
Напортачил ещё с версией 1.2.6, в 1.2.7 всё должно работать

**Comment by Aleck85** [comment]
З.Ы. А нельзя ли сделать иконку как раньше - белые цифры на красном фоне, а то черное на красном не очень хорошо различимо?

**Comment by RunninglVlan** [comment]
Будет ;)
Этот цвет только в Firefox можно менять, в Chromium по умолчанию белый

**Comment by Aleck85** [comment]
А есть версия под chromium? Ее можно где-то скачать? А можно сделать совместимую версию для microsoft edge?

**Comment by RunninglVlan** [comment]
Этот репозиторий - и есть версия для Chromium. Я изначально делал расширение для Opera, так как ей в основном пользуюсь. Потом залил ещё в магазины Chrome и Firefox. Из магазинов Opera и Chrome расширение удалили, так как от Facebook пожаловались на их картинки, слова. Надо было сделать, чтобы не было похоже, что это их продукт. Но у меня не доходят до этого руки, да и немного не мои способности для этого нужны =)
Opera/Chrome/Edge - у них под капотом Chromium, а у Firefox почти так же расширения работают, так что это расширение тоже для него подходит.
Это расширение можно установить из папки, надо только войти в Developer Mode и Install Unpacked Extension. Что-то такое (или эквивалент на русском).
Попробовал запустить на Edge - но там ругается на функционал, который есть только в Firefox. Могу это пофиксить, но заливать на их магазин пока не планирую, не вижу смысла, скорее всего оттуда тоже удалят. Из Firefox по какому-то счастливому случаю не удаляют =D
Если не сложно, создай новый Issue, что расширение не работает в Edge, если, конечно, готов его запускать не из магазина. Как будет время, я пофикшу

**Comment by Aleck85** [comment]
Жаль. Просто в магазине chrome есть расширения с похожим функционалом (например, [вот](https://chrome.google.com/webstore/detail/notifier-for-facebook/ocgmcodaanlenepilchadlnabakhgaoi) или [вот](https://chrome.google.com/webstore/detail/f-notifier/befpdcighpikpkklmfonkmdafmfnnkfn) ) и их никто не удаляет, но авторы на них подзабили и сейчас они не работают.

**Comment by RunninglVlan** [comment]
У них иконки свои и названия изменены, да
