### ISSUE TITLE
Version for Chrome

### ISSUE THREAD

**Issue by Aleck85** [RunninglVlan/Facebook-Status#2]
It would be great to have the Chrome version.

**Comment by RunninglVlan** [comment]
@Aleck85, do you know about Facebook Push Notifications for Chrome? For example, [this article](http://www.omgchrome.com/how-to-enable-facebook-notifications-chrome/) describes functionality.

**Comment by Aleck85** [comment]
I tried, but I could not. Besides, for me default chrome poup notifications are not so good as tollbar icons.

**Comment by RunninglVlan** [comment]
I was planning to publish Facebook Status to Chrome Web Store today, but found out that developers need to pay one-time registration fee of US$5.00 to verify their accounts.
As Chrome is not my primary browser and I'm using it quite rarely, I don't particularly want to pay anything to let others use my free extension on Chrome.

But I would probably close my eyes to this fee if I'd see that a lot of people want this extension on Chrome. =D

In the meantime you could try downloading ZIP of this repository to your PC, unzipping it and load unpacked extension using Chrome's Developer mode on its Extensions page. That way you could already use this extension, although Chrome would suggest to Disable it after every Chrome's restart. =)

**Comment by RunninglVlan** [comment]
@Aleck85 I finally added my extension to the Chrome Web Store
https://chrome.google.com/webstore/detail/facebook-status/pmgibfcomaiaigfapndkcjilfjegjmfl
Please try it and tell me if something's not working correctly

**Comment by Aleck85** [comment]
It works well, thank you very much.
