### ISSUE TITLE
Extension does not create new tab

### ISSUE THREAD

**Issue by Nekomajin42** [RunninglVlan/Facebook-Status#3]
Hello!

A strange error appeared after I updated to Opera 36 today. The toolbar icon does not create a new tab on click, no matter if there is any kind of notification or not. No matter if Facebook is open or not.

It is even stranger that if I have messeger.com open, the extension button activates that tab on click.

**Comment by RunninglVlan** [comment]
My bad, I probably saw that url parameter for method [chrome.tabs.query](https://developer.chrome.com/extensions/tabs#method-query) requires tabs permission and still removed this permission as it worked fine in previous versions of Opera.

**Comment by RunninglVlan** [comment]
Hm, actually, it's Opera's fault. =D I'm uploading update right now and Opera tells me 

> Not all declared permissions are used. tabs are not required.

Probably that's why I removed this permission in the first place. Got to remember this. =)

**Comment by Nekomajin42** [comment]
Thanks!
