### ISSUE TITLE
Icon number

### ISSUE THREAD

**Issue by Aleck85** [RunninglVlan/Facebook-Status#7]
Icon number doesent display correctly in Vivaldi. Please fix.
![default](https://cloud.githubusercontent.com/assets/5072865/18025879/a3ba4e10-6c3f-11e6-808b-9fb9150c2ab9.JPG)

**Comment by RunninglVlan** [comment]
With latest version for Chrome ([1.2.1](https://chrome.google.com/webstore/detail/facebook-status/pmgibfcomaiaigfapndkcjilfjegjmfl)) it should be fine, although I don't particularly like the size of icon in Vivaldi. I think, it's too big.
![image](https://cloud.githubusercontent.com/assets/11376741/18030065/9b08623e-6cb2-11e6-8f63-407714eb9fae.png)
I like Opera's icons the most =)
