### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by Aleck85** [RunninglVlan/Facebook-Status#9]
Do you plan to make Firefox version?

**Comment by RunninglVlan** [comment]
Unfortunately, this extensions was taken down from Opera and Chrome stores (#8). I don't know when I'll get back to it. I need to change it first, before adding new features and making versions for other browsers.

**Comment by RunninglVlan** [comment]
I checked and no modifications are required to use this extension in Firefox. So I see 2 options for you to use it:
* Just download the source code, e.g. using link [Download ZIP](https://github.com/RunninglVlan/Facebook-Status/archive/master.zip), unzip the archive, open _about:debugging_ in Firefox, click on _Load Temporary Add-on_, navigate to extension's folder and choose any file inside it, e.g. manifest.json. You'll be using the extension until Firefox restart. [Here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) is How-to from Firefox
* If you don't like 1st option, I will upload extension to https://addons.mozilla.org/ for Firefox to sign it

**Comment by Aleck85** [comment]
Very good news! I would prefer to see it on addons.mozilla.
Many, many thanks!!!

**Comment by Aleck85** [comment]
Hm, I can't download this
![_1_](https://user-images.githubusercontent.com/5072865/30518623-3ddd1b72-9b8c-11e7-941f-4205a7d5b371.jpg)

**Comment by Aleck85** [comment]
It's work now!!!

**Comment by Aleck85** [comment]
It woul be great to make redirection to facebook.com instead of facebook.com/notifications on click (f.e. if I have several different kinds of notifications at the same time - page facebook.com/notifications is uncomfortable).

**Comment by RunninglVlan** [comment]
Yeah, as you already noticed, extension is live here: https://addons.mozilla.org/en-US/firefox/addon/facebook-status/

I think you already wrote about notifications in #5 =)
